name: Java CI/CD with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Make mvnw executable
      run: chmod +x mvnw

    - name: Build with Maven
      run: ./mvnw clean package

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Lowercase repository name
      id: string
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ github.repository }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/${{ steps.string.outputs.lowercase }}:latest
